### ISSUE TITLE
Wait for async I/O completion

### ISSUE THREAD

**Issue by ehmicky** [quarva/netlify-plugin-contextual-redirects#5]
The Build plugin event handlers should complete only once all its logic has completed. This includes asynchronous I/O.

[Link to the relevant section in the documentation](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#asynchronous-code).

However, this is not the case in the following cases:
  - When copying the redirects file at https://github.com/quarva/netlify-plugin-contextual-redirects/blob/56b15f1befbaef7a78f8a1fd10bcfc60d76f8d1e/index.js#L53
  - When reading the redirects file at https://github.com/quarva/netlify-plugin-contextual-redirects/blob/56b15f1befbaef7a78f8a1fd10bcfc60d76f8d1e/index.js#L75

This plugin should use [`fs.promises`](https://nodejs.org/api/fs.html#fs_fs_promises_api) instead. For example:

```js
try {
  await fs.promise.copyFile(redirect_source, publish_dir + '/_redirects')
} catch (err) {
  return failBuild('Couldn\'t write _redirects: ' + err);
}
Logger.debug('Wrote _redirects successfully.');	
```

and:

```js
let data
try {
  data = await fs.promises.readFile(redirect_source)
} catch (err) {
  return failBuild('Couldn\'t read the specified redirects_file: ' + err);
}
const redirects = '\n\n' + data;

Logger.debug('Preparing to append redirects...');
Logger.debug('Appending redirects...');  

try {
  await fs.promises.appendFile(config_file,redirects);
} catch(err) {
  return failBuild('Error while appending redirects: ' + err);
}
Logger.debug('Done.');
```

**Comment by culturestate** [comment]
Would it be better to instead use e.g. `copyFileSync` in this case, since they're necessarily sequential operations anyway?

**Comment by ehmicky** [comment]
Going back to the original problem (plugin event handler should not complete until all its operations have completed), synchronous I/O would fix this problem as well. That being said, async I/O [is encouraged](https://nodejs.org/en/knowledge/getting-started/control-flow/how-to-write-asynchronous-code/) as it promotes better performance, even in serial operations. Either solution works though :+1:

**Comment by ehmicky** [comment]
Thanks @culturestate!

One small thing: you might have forgotten to prepend `await` to the following lines:

https://github.com/quarva/netlify-plugin-contextual-redirects/blob/0dee5b6dd882e6f4d4833f760ae0a1717bf7e37a/index.js#L58

https://github.com/quarva/netlify-plugin-contextual-redirects/blob/0dee5b6dd882e6f4d4833f760ae0a1717bf7e37a/index.js#L89

Without `await`, the function will return without waiting for the `async` function to complete.
